name: Release Please

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      HAS_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN != '' }}
    steps:
      - uses: googleapis/release-please-action@v4
        if: ${{ env.HAS_TOKEN == 'true' }}
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
